<?php

namespace Database\Seeders;

use App\Models\Order;
use App\Models\OrderItem;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('order_items')->delete();
        DB::table('orders')->delete();
        DB::table('products')->delete();
        DB::table('users')->delete();

        $admin = User::create([
            'name' => 'Admin User',
            'email' => 'admin@dustypages.test',
            'username' => 'dusty_admin',
            'phone' => '+63 912 000 0000',
            'favorite_genre' => 'Classic Literature',
            'is_admin' => true,
            'password' => Hash::make('password'),
        ]);

        $customer = User::create([
            'name' => 'Juan dela Cruz',
            'email' => 'juan@email.com',
            'username' => 'bookworm_juan',
            'phone' => '+63 912 345 6789',
            'favorite_genre' => 'Classic Literature',
            'is_admin' => false,
            'password' => Hash::make('password123'),
        ]);

        $products = collect([
            [
                'title' => 'Great Expectations',
                'slug' => 'great-expectations',
                'author' => 'Charles Dickens',
                'genre' => 'Classic Fiction',
                'category' => 'Classic Literature',
                'description' => 'The story of young orphan Pip and his rise through wealth and longing in Victorian England, presented as a lovingly restored digital edition.',
                'price' => 249,
                'original_price' => 349,
                'rating' => 4.8,
                'review_count' => 1243,
                'stock' => 28,
                'is_active' => true,
                'badge' => 'Bestseller',
                'cover_emoji' => '📖',
                'cover_class' => 'b1',
                'cover_gradient' => 'linear-gradient(135deg,#5c2e0a,#8b4513)',
                'formats' => ['ePub', 'PDF', 'MOBI'],
                'pages' => 544,
                'language' => 'English',
                'published_label' => '1861 · Restored Ed.',
                'is_featured' => true,
                'sort_order' => 1,
                'image' => 'great-expectations.jpg',
            ],
            [
                'title' => 'Moby Dick',
                'slug' => 'moby-dick',
                'author' => 'Herman Melville',
                'genre' => 'Adventure',
                'category' => 'Adventure',
                'description' => 'A storm-tossed voyage of obsession, fate, and the sea, carefully typeset for modern readers.',
                'price' => 199,
                'original_price' => null,
                'rating' => 4.4,
                'review_count' => 831,
                'stock' => 15,
                'is_active' => true,
                'badge' => 'New',
                'cover_emoji' => '🌊',
                'cover_class' => 'b2',
                'cover_gradient' => 'linear-gradient(135deg,#1a3a2a,#2d6a4f)',
                'formats' => ['ePub', 'PDF', 'MOBI'],
                'pages' => 720,
                'language' => 'English',
                'published_label' => '1851 · Sea Edition',
                'is_featured' => true,
                'sort_order' => 2,
                'image' => 'moby-dick.jpg',
            ],
            [
                'title' => 'Jane Eyre',
                'slug' => 'jane-eyre',
                'author' => 'Charlotte Brontë',
                'genre' => 'Gothic Romance',
                'category' => 'Romance',
                'description' => 'A fierce and tender Gothic romance with a restored layout and archival-inspired cover treatment.',
                'price' => 229,
                'original_price' => null,
                'rating' => 5.0,
                'review_count' => 1104,
                'stock' => 22,
                'is_active' => true,
                'badge' => null,
                'cover_emoji' => '🏰',
                'cover_class' => 'b3',
                'cover_gradient' => 'linear-gradient(135deg,#2a1a4a,#4a2d8a)',
                'formats' => ['ePub', 'PDF', 'MOBI'],
                'pages' => 532,
                'language' => 'English',
                'published_label' => '1847 · Collector Edition',
                'is_featured' => true,
                'sort_order' => 3,
                'image' => 'jane-eyre.jpg',
            ],
            [
                'title' => 'Don Quixote',
                'slug' => 'don-quixote',
                'author' => 'Miguel de Cervantes',
                'genre' => 'Epic Satire',
                'category' => 'Classic Literature',
                'description' => 'The immortal quest of the knight of La Mancha, formatted for comfortable digital reading.',
                'price' => 179,
                'original_price' => 229,
                'rating' => 4.2,
                'review_count' => 540,
                'stock' => 2,
                'is_active' => true,
                'badge' => 'Sale',
                'cover_emoji' => '⚔️',
                'cover_class' => 'b4',
                'cover_gradient' => 'linear-gradient(135deg,#3a2a0a,#8b7a2a)',
                'formats' => ['ePub', 'PDF', 'MOBI'],
                'pages' => 992,
                'language' => 'English',
                'published_label' => '1605 · Modern Translation',
                'is_featured' => false,
                'sort_order' => 4,
                'image' => 'treasure-island.jpg',
            ],
            [
                'title' => 'Dracula',
                'slug' => 'dracula',
                'author' => 'Bram Stoker',
                'genre' => 'Gothic Horror',
                'category' => 'Gothic & Horror',
                'description' => 'A richly atmospheric horror classic that arrives in beautifully restored digital formats.',
                'price' => 219,
                'original_price' => null,
                'rating' => 4.9,
                'review_count' => 975,
                'stock' => 18,
                'is_active' => false,
                'badge' => null,
                'cover_emoji' => '💀',
                'cover_class' => 'b5',
                'cover_gradient' => 'linear-gradient(135deg,#4a1a1a,#8b2020)',
                'formats' => ['ePub', 'PDF', 'MOBI'],
                'pages' => 418,
                'language' => 'English',
                'published_label' => '1897 · Midnight Edition',
                'is_featured' => false,
                'sort_order' => 5,
                'image' => 'dracula.jpg',
            ],
            [
                'title' => 'Frankenstein',
                'slug' => 'frankenstein',
                'author' => 'Mary Shelley',
                'genre' => 'Science & Horror',
                'category' => 'Science & History',
                'description' => 'Shelley’s seminal tale of creation and consequence in a carefully curated digital facsimile.',
                'price' => 209,
                'original_price' => null,
                'rating' => 4.7,
                'review_count' => 882,
                'stock' => 5,
                'is_active' => true,
                'badge' => null,
                'cover_emoji' => '🔬',
                'cover_class' => 'b6',
                'cover_gradient' => 'linear-gradient(135deg,#1a2a3a,#2a4a6a)',
                'formats' => ['ePub', 'PDF', 'MOBI'],
                'pages' => 320,
                'language' => 'English',
                'published_label' => '1818 · Laboratory Edition',
                'is_featured' => true,
                'sort_order' => 6,
                'image' => 'frankenstein.jpg',
            ],
            [
                'title' => 'Thus Spoke Zarathustra',
                'slug' => 'thus-spoke-zarathustra',
                'author' => 'Friedrich Nietzsche',
                'genre' => 'Philosophy',
                'category' => 'Philosophy',
                'description' => 'Nietzsche’s lyrical philosophical work with clean reading modes and polished typography.',
                'price' => 259,
                'original_price' => null,
                'rating' => 4.6,
                'review_count' => 368,
                'stock' => 4,
                'is_active' => true,
                'badge' => null,
                'cover_emoji' => '🕊️',
                'cover_class' => 'b7',
                'cover_gradient' => 'linear-gradient(135deg,#2a3a1a,#4a6a2a)',
                'formats' => ['ePub', 'PDF', 'MOBI'],
                'pages' => 352,
                'language' => 'English',
                'published_label' => '1883 · Annotated Edition',
                'is_featured' => false,
                'sort_order' => 7,
                'image' => 'meditations.jpg',
            ],
            [
                'title' => 'Wuthering Heights',
                'slug' => 'wuthering-heights',
                'author' => 'Emily Brontë',
                'genre' => 'Gothic Romance',
                'category' => 'Romance',
                'description' => 'A windswept romance rendered in warm sepia tones and clean eBook layouts.',
                'price' => 189,
                'original_price' => null,
                'rating' => 4.5,
                'review_count' => 690,
                'stock' => 12,
                'is_active' => true,
                'badge' => null,
                'cover_emoji' => '🌹',
                'cover_class' => 'b8',
                'cover_gradient' => 'linear-gradient(135deg,#3a1a2a,#6a2a4a)',
                'formats' => ['ePub', 'PDF', 'MOBI'],
                'pages' => 402,
                'language' => 'English',
                'published_label' => '1847 · Moors Edition',
                'is_featured' => false,
                'sort_order' => 8,
                'image' => 'wuthering-heights.jpg',
            ],
            [
                'title' => 'The Republic',
                'slug' => 'the-republic',
                'author' => 'Plato',
                'genre' => 'Philosophy',
                'category' => 'Philosophy',
                'description' => 'Plato’s dialogues on justice and order, tuned for long-form digital study.',
                'price' => 239,
                'original_price' => null,
                'rating' => 4.3,
                'review_count' => 402,
                'stock' => 1,
                'is_active' => true,
                'badge' => null,
                'cover_emoji' => '🏛️',
                'cover_class' => 'b9',
                'cover_gradient' => 'linear-gradient(135deg,#2a2a1a,#5a5a2a)',
                'formats' => ['ePub', 'PDF', 'MOBI'],
                'pages' => 416,
                'language' => 'English',
                'published_label' => '375 BC · Scholar Edition',
                'is_featured' => false,
                'sort_order' => 9,
                'image' => 'the-republic.jpg',
            ],
        ])->map(fn (array $product) => Product::create($product));

        $order = Order::create([
            'user_id' => $customer->id,
            'order_number' => 'DP-2024-00847',
            'status' => 'Pending',
            'payment_method' => 'Cash on Delivery',
            'payment_status' => 'Pending',
            'shipping_name' => 'Juan dela Cruz',
            'shipping_email' => 'juan@email.com',
            'shipping_phone' => '+63 912 345 6789',
            'shipping_address' => '123 Rizal St, Brgy San Jose',
            'shipping_city' => 'Manila',
            'shipping_province' => 'Metro Manila',
            'shipping_zip' => '1000',
            'shipping_country' => 'Philippines',
            'delivery_notes' => 'Leave package at the front desk if unavailable.',
            'subtotal' => 916,
            'shipping_fee' => 0,
            'total' => 916,
            'created_at' => now()->subDays(2),
            'updated_at' => now()->subDays(2),
        ]);

        foreach ([
            ['slug' => 'great-expectations', 'qty' => 1, 'line_total' => 249],
            ['slug' => 'jane-eyre', 'qty' => 1, 'line_total' => 229],
            ['slug' => 'dracula', 'qty' => 2, 'line_total' => 438],
        ] as $item) {
            $product = $products->firstWhere('slug', $item['slug']);

            OrderItem::create([
                'order_id' => $order->id,
                'product_id' => $product->id,
                'product_title' => $product->title,
                'product_author' => $product->author,
                'cover_emoji' => $product->cover_emoji,
                'cover_class' => $product->cover_class,
                'formats' => $product->formats,
                'quantity' => $item['qty'],
                'unit_price' => $product->price,
                'line_total' => $item['line_total'],
                'created_at' => $order->created_at,
                'updated_at' => $order->updated_at,
            ]);
        }
    }
}
